# Generated by Django 4.2.4 on 2023-08-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='sellerEmailId',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
