# Generated by Django 4.2.4 on 2023-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerModel',
            fields=[
                ('buyerId', models.IntegerField(primary_key=True, serialize=False)),
                ('buyerName', models.CharField(max_length=50)),
                ('buyerDetails', models.TextField(null=True)),
                ('buyerEmailId', models.CharField(max_length=100, unique=True)),
                ('buyerPassword', models.CharField(max_length=12)),
                ('buyerContactNo', models.CharField(max_length=12)),
            ],
        ),
    ]
