# Generated by Django 4.2.4 on 2023-08-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_productmodel_categoryid'),
        ('buyers', '0002_alter_buyermodel_buyeremailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cartId', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='buyers.buyermodel')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productmodel')),
            ],
        ),
    ]
