# Generated by Django 4.2.4 on 2023-08-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_categoryid'),
        ('cart', '0002_alter_cartmodel_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productmodel'),
        ),
    ]
