# Generated by Django 4.2.4 on 2023-08-04 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_category_categorymodel'),
        ('sellers', '0001_initial'),
        ('products', '0002_remove_productmodel_id_productmodel_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.sellermodel'),
        ),
    ]
