# Generated by Django 4.2.4 on 2023-08-04 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_category_categorymodel'),
        ('products', '0004_alter_productmodel_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.categorymodel'),
        ),
    ]
